version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/tmp
      -  ./app:/app
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development